is_server: false

ipv6: false

tun:
  if_name: auto
  mtu: 1280
  local_tun_ip: 192.168.192.100
  remote_tun_ip: auto
  local_tun_ip6: auto
  remote_tun_ip6: auto

route:
  default_route: true

conn_key: 12345678
conn_protocol: udp

server_ip_or_name: 108.21.112.76
server_port: 1800


